<?php do_action( 'get_header', null ) ?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="<?php bloginfo( 'charset' ); ?>">
    <meta name="viewport"
          content="initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no,  width=device-width">
    <meta name="format-detection" content="telephone=no">
    <title>
        <?php bloginfo( 'name' ); wp_title( '|', true, 'left' ); ?>
    </title>
    <?php wp_head(); ?>
</head>

<body <?php body_class($this->screen()->which()) ?>>
