<p>
    <label for="<?=$fieldName?>"><?=$name?></label>
    <br />
    <select name="<?=$fieldName?>" id="<?=$fieldName?>" style="width: 97%;">
        <?php
        $selected = get_post_meta( $object->ID, $name, true );
        if (empty($selected)) {
            echo '<option value="" selected="true">Default Static Controller</option>';
        } else {
            echo '<option value="">Default Static Controller</option>';
        }
        
        foreach ($readAllControllersFromFS() as $controller) {
            if ($selected === $controller) {
                echo '<option value="'.$controller.'" selected="true">'.$controller.'</option>';
            } else {
                echo '<option value="'.$controller.'">'.$controller.'</option>';
            }
        }
        ?>
    </select>
    <input type="hidden" name="<?=$fieldName?>-nonce"
           value="<?php echo wp_create_nonce( plugin_basename( $file ) ); ?>" />

</p>
