<?php
/*  Copyright Mil's (http://milsdev.com/)

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
*/
?>
<p>
    <label for="<?=$fieldName?>"><?=$name?></label>
    <br />
    <select name="<?=$fieldName?>" id="<?=$fieldName?>" style="width: 97%;">
        <?php
        $selected = get_post_meta( $object->ID, $name, true );
        if (empty($selected)) {
            echo '<option value="" selected="true">Default Static Controller</option>';
        } else {
            echo '<option value="">Default Static Controller</option>';
        }
        
        foreach ($readAllControllersFromFS() as $controller) {
            if ($selected === $controller) {
                echo '<option value="'.$controller.'" selected="true">'.$controller.'</option>';
            } else {
                echo '<option value="'.$controller.'">'.$controller.'</option>';
            }
        }
        ?>
    </select>
    <input type="hidden" name="<?=$fieldName?>-nonce"
           value="<?php echo wp_create_nonce( plugin_basename( $file ) ); ?>" />

</p>
