<?php
namespace Sarcofag\Service\API;


/**
 * Class WP
 * @package Sarcofag\API
 *
 * @method _
 * @method __
 * @method __autoload
 * @method __checked_selected_helper
 * @method __clear_multi_author_cache
 * @method __get_option
 * @method __ngettext
 * @method __ngettext_noop
 * @method __return_empty_array
 * @method __return_empty_string
 * @method __return_false
 * @method __return_null
 * @method __return_true
 * @method __return_zero
 * @method _access_denied_splash
 * @method _add_post_type_submenus
 * @method _add_themes_utility_last
 * @method _admin_bar_bump_cb
 * @method _admin_notice_post_locked
 * @method _admin_search_query
 * @method _ajax_wp_die_handler
 * @method _autop_newline_preservation_helper
 * @method _backup_plugin_globals
 * @method _c
 * @method _canonical_charset
 * @method _cleanup_header_comment
 * @method _cleanup_image_add_caption
 * @method _close_comments_for_old_post
 * @method _close_comments_for_old_posts
 * @method _config_wp_home
 * @method _config_wp_siteurl
 * @method _convert_urlencoded_to_entities
 * @method _copy_dir
 * @method _copy_image_file
 * @method _count_posts_cache_key
 * @method _crop_image_resource
 * @method _custom_background_cb
 * @method _custom_header_background_just_in_time
 * @method _custom_logo_header_styles
 * @method _deep_replace
 * @method _default_wp_die_handler
 * @method _delete_attachment_theme_mod
 * @method _deprecated_argument
 * @method _deprecated_constructor
 * @method _deprecated_file
 * @method _deprecated_function
 * @method _deprecated_hook
 * @method _device_can_upload
 * @method _doing_it_wrong
 * @method _draft_or_post_title
 * @method _e
 * @method _ex
 * @method _fetch_remote_file
 * @method _fix_attachment_links
 * @method _flip_image_resource
 * @method _future_post_hook
 * @method _get_additional_user_keys
 * @method _get_admin_bar_pref
 * @method _get_cron_array
 * @method _get_cron_lock
 * @method _get_custom_object_labels
 * @method _get_dropins
 * @method _get_last_post_time
 * @method _get_list_table
 * @method _get_meta_table
 * @method _get_non_cached_ids
 * @method _get_page_link
 * @method _get_plugin_data_markup_translate
 * @method _get_post_ancestors
 * @method _get_random_header_data
 * @method _get_template_edit_filename
 * @method _get_term_children
 * @method _get_term_hierarchy
 * @method _get_widget_id_base
 * @method _get_wptexturize_shortcode_regex
 * @method _get_wptexturize_split_regex
 * @method _hash_hmac
 * @method _http_build_query
 * @method _image_get_preview_ratio
 * @method _insert_into_post_button
 * @method _ipad_meta
 * @method _is_valid_nav_menu_item
 * @method _json_decode_object_helper
 * @method _links_add_base
 * @method _links_add_target
 * @method _list_meta_row
 * @method _load_image_to_edit_path
 * @method _load_textdomain_just_in_time
 * @method _local_storage_notice
 * @method _make_cat_compat
 * @method _make_email_clickable_cb
 * @method _make_url_clickable_cb
 * @method _make_web_ftp_clickable_cb
 * @method _maybe_update_core
 * @method _maybe_update_plugins
 * @method _maybe_update_themes
 * @method _mb_strlen
 * @method _mb_substr
 * @method _mce_set_direction
 * @method _media_button
 * @method _media_states
 * @method _n
 * @method _n_noop
 * @method _nav_menu_item_id_use_once
 * @method _navigation_markup
 * @method _nc
 * @method _nx
 * @method _nx_noop
 * @method _oembed_create_xml
 * @method _oembed_filter_feed_content
 * @method _oembed_rest_pre_serve_request
 * @method _pad_term_counts
 * @method _page_traverse_name
 * @method _post_format_get_term
 * @method _post_format_get_terms
 * @method _post_format_link
 * @method _post_format_request
 * @method _post_format_wp_get_object_terms
 * @method _post_states
 * @method _post_type_meta_capabilities
 * @method _preview_theme_stylesheet_filter
 * @method _preview_theme_template_filter
 * @method _prime_comment_caches
 * @method _prime_network_caches
 * @method _prime_post_caches
 * @method _prime_site_caches
 * @method _prime_term_caches
 * @method _print_emoji_detection_script
 * @method _print_scripts
 * @method _print_styles
 * @method _publish_post_hook
 * @method _redirect_to_about_wordpress
 * @method _register_widget_form_callback
 * @method _register_widget_update_callback
 * @method _relocate_children
 * @method _remove_qs_args_if_not_in_url
 * @method _remove_theme_support
 * @method _reset_front_page_settings_for_post
 * @method _response_to_rss
 * @method _restore_plugin_globals
 * @method _rotate_image_resource
 * @method _save_post_hook
 * @method _scalar_wp_die_handler
 * @method _search_terms_tidy
 * @method _set_cron_array
 * @method _set_preview
 * @method _show_post_preview
 * @method _sort_name_callback
 * @method _sort_nav_menu_items
 * @method _sort_uname_callback
 * @method _split_shared_term
 * @method _split_str_by_whitespace
 * @method _thickbox_path_admin_subfolder
 * @method _transition_post_status
 * @method _truncate_post_slug
 * @method _unzip_file_pclzip
 * @method _unzip_file_ziparchive
 * @method _update_blog_date_on_post_delete
 * @method _update_blog_date_on_post_publish
 * @method _update_generic_term_count
 * @method _update_post_term_count
 * @method _update_posts_count_on_delete
 * @method _update_posts_count_on_transition_post_status
 * @method _update_term_count_on_transition_post_status
 * @method _upgrade_422_find_genericons_files_in_folder
 * @method _upgrade_422_remove_genericons
 * @method _upgrade_440_force_deactivate_incompatible_plugins
 * @method _upgrade_cron_array
 * @method _usort_by_first_member
 * @method _usort_terms_by_id
 * @method _usort_terms_by_name
 * @method _walk_bookmarks
 * @method _wp_add_global_attributes
 * @method _wp_admin_bar_init
 * @method _wp_admin_html_begin
 * @method _wp_ajax_add_hierarchical_term
 * @method _wp_ajax_delete_comment_response
 * @method _wp_ajax_menu_quick_search
 * @method _wp_auto_add_pages_to_menu
 * @method _wp_batch_split_terms
 * @method _wp_call_all_hook
 * @method _wp_can_use_pcre_u
 * @method _wp_check_for_scheduled_split_terms
 * @method _wp_check_split_default_terms
 * @method _wp_check_split_nav_menu_terms
 * @method _wp_check_split_terms_in_menus
 * @method _wp_credits_add_profile_link
 * @method _wp_credits_build_object_link
 * @method _wp_customize_include
 * @method _wp_customize_loader_settings
 * @method _wp_dashboard_control_callback
 * @method _wp_dashboard_recent_comments_row
 * @method _wp_delete_orphaned_draft_menu_items
 * @method _wp_delete_post_menu_item
 * @method _wp_delete_tax_menu_item
 * @method _wp_expand_nav_menu_post_data
 * @method _wp_filter_build_unique_id
 * @method _wp_filter_taxonomy_base
 * @method _wp_footer_scripts
 * @method _wp_get_attachment_relative_path
 * @method _wp_get_current_user
 * @method _wp_get_image_size_from_meta
 * @method _wp_get_post_revision_version
 * @method _wp_get_user_contactmethods
 * @method _wp_handle_upload
 * @method _wp_http_get_object
 * @method _wp_image_editor_choose
 * @method _wp_iso_convert
 * @method _wp_json_convert_string
 * @method _wp_json_prepare_data
 * @method _wp_json_sanity_check
 * @method _wp_kses_decode_entities_chr
 * @method _wp_kses_decode_entities_chr_hexdec
 * @method _wp_kses_split_callback
 * @method _wp_link_page
 * @method _wp_menu_item_classes_by_context
 * @method _wp_menu_output
 * @method _wp_mysql_week
 * @method _wp_nav_menu_meta_box_object
 * @method _wp_object_count_sort_cb
 * @method _wp_object_name_sort_cb
 * @method _wp_oembed_get_object
 * @method _wp_post_revision_data
 * @method _wp_post_revision_fields
 * @method _wp_post_thumbnail_class_filter
 * @method _wp_post_thumbnail_class_filter_add
 * @method _wp_post_thumbnail_class_filter_remove
 * @method _wp_post_thumbnail_html
 * @method _wp_posts_page_notice
 * @method _wp_preview_terms_filter
 * @method _wp_put_post_revision
 * @method _wp_register_meta_args_whitelist
 * @method _wp_relative_upload_path
 * @method _wp_render_title_tag
 * @method _wp_sanitize_utf8_in_redirect
 * @method _wp_scripts_maybe_doing_it_wrong
 * @method _wp_sidebars_changed
 * @method _wp_specialchars
 * @method _wp_timezone_choice_usort_callback
 * @method _wp_translate_postdata
 * @method _wp_upgrade_revisions_of_post
 * @method _wp_upload_dir
 * @method _wptexturize_pushpop_element
 * @method _x
 * @method _xmlrpc_wp_die_handler
 * @method absint
 * @method activate_plugin
 * @method activate_plugins
 * @method activate_sitewide_plugin
 * @method add_action
 * @method add_blog_option
 * @method add_clean_index
 * @method add_comment_meta
 * @method add_comments_page
 * @method add_contextual_help
 * @method add_cssclass
 * @method add_custom_background
 * @method add_custom_image_header
 * @method add_dashboard_page
 * @method add_editor_style
 * @method add_existing_user_to_blog
 * @method add_feed
 * @method add_filter
 * @method add_image_size
 * @method add_link
 * @method add_links_page
 * @method add_magic_quotes
 * @method add_management_page
 * @method add_media_page
 * @method add_menu_classes
 * @method add_menu_page
 * @method add_meta
 * @method add_meta_box
 * @method add_metadata
 * @method add_network_option
 * @method add_new_user_to_blog
 * @method add_object_page
 * @method add_option
 * @method add_option_update_handler
 * @method add_option_whitelist
 * @method add_options_page
 * @method add_pages_page
 * @method add_permastruct
 * @method add_ping
 * @method add_plugins_page
 * @method add_post_meta
 * @method add_post_type_support
 * @method add_posts_page
 * @method add_query_arg
 * @method add_rewrite_endpoint
 * @method add_rewrite_rule
 * @method add_rewrite_tag
 * @method add_role
 * @method add_screen_option
 * @method add_settings_error
 * @method add_settings_field
 * @method add_settings_section
 * @method add_shortcode
 * @method add_site_option
 * @method add_submenu_page
 * @method add_term_meta
 * @method add_theme_page
 * @method add_theme_support
 * @method add_thickbox
 * @method add_user
 * @method add_user_meta
 * @method add_user_to_blog
 * @method add_users_page
 * @method add_utility_page
 * @method addslashes_gpc
 * @method adjacent_image_link
 * @method adjacent_post_link
 * @method adjacent_posts_rel_link
 * @method adjacent_posts_rel_link_wp_head
 * @method admin_color_scheme_picker
 * @method admin_created_user_email
 * @method admin_url
 * @method allow_subdirectory_install
 * @method allow_subdomain_install
 * @method allowed_http_request_hosts
 * @method allowed_tags
 * @method antispambot
 * @method apache_mod_loaded
 * @method apply_filters
 * @method apply_filters_deprecated
 * @method apply_filters_ref_array
 * @method array_replace_recursive
 * @method atom_enclosure
 * @method atom_site_icon
 * @method attachment_id3_data_meta_box
 * @method attachment_submit_meta_box
 * @method attachment_submitbox_metadata
 * @method attachment_url_to_postid
 * @method attribute_escape
 * @method auth_redirect
 * @method author_can
 * @method automatic_feed_links
 * @method avoid_blog_page_permalink_collision
 * @method background_color
 * @method background_image
 * @method backslashit
 * @method balancetags
 * @method before_last_bar
 * @method bloginfo
 * @method bloginfo_rss
 * @method body_class
 * @method bool_from_yn
 * @method build_query
 * @method bulk_edit_posts
 * @method cache_javascript_headers
 * @method cache_users
 * @method calendar_week_mod
 * @method can_edit_network
 * @method cancel_comment_reply_link
 * @method capital_p_dangit
 * @method cat_is_ancestor_of
 * @method category_description
 * @method category_exists
 * @method check_admin_referer
 * @method check_ajax_referer
 * @method check_and_publish_future_post
 * @method check_column
 * @method check_comment
 * @method check_comment_flood_db
 * @method check_import_new_users
 * @method check_password_reset_key
 * @method check_theme_switched
 * @method check_upload_mimes
 * @method check_upload_size
 * @method checked
 * @method choose_primary_blog
 * @method clean_attachment_cache
 * @method clean_blog_cache
 * @method clean_bookmark_cache
 * @method clean_category_cache
 * @method clean_comment_cache
 * @method clean_network_cache
 * @method clean_object_term_cache
 * @method clean_page_cache
 * @method clean_post_cache
 * @method clean_pre
 * @method clean_term_cache
 * @method clean_url
 * @method clean_user_cache
 * @method clear_global_post_cache
 * @method codepress_footer_js
 * @method codepress_get_lang
 * @method comment_author
 * @method comment_author_email
 * @method comment_author_email_link
 * @method comment_author_ip
 * @method comment_author_link
 * @method comment_author_rss
 * @method comment_author_url
 * @method comment_author_url_link
 * @method comment_class
 * @method comment_date
 * @method comment_excerpt
 * @method comment_exists
 * @method comment_footer_die
 * @method comment_form
 * @method comment_form_title
 * @method comment_guid
 * @method comment_id
 * @method comment_id_fields
 * @method comment_link
 * @method comment_reply_link
 * @method comment_text
 * @method comment_text_rss
 * @method comment_time
 * @method comment_type
 * @method comments_link
 * @method comments_link_feed
 * @method comments_number
 * @method comments_open
 * @method comments_popup_link
 * @method comments_popup_script
 * @method comments_rss
 * @method comments_rss_link
 * @method comments_template
 * @method compression_test
 * @method confirm_another_blog_signup
 * @method confirm_blog_signup
 * @method confirm_delete_users
 * @method confirm_user_signup
 * @method content_url
 * @method convert_chars
 * @method convert_invalid_entities
 * @method convert_smilies
 * @method convert_to_screen
 * @method copy_dir
 * @method core_update_footer
 * @method core_upgrade_preamble
 * @method count_many_users_posts
 * @method count_user_posts
 * @method count_users
 * @method create_empty_blog
 * @method create_initial_post_types
 * @method create_initial_taxonomies
 * @method create_user
 * @method current_action
 * @method current_filter
 * @method current_theme_info
 * @method current_theme_supports
 * @method current_time
 * @method current_user_can
 * @method current_user_can_for_blog
 * @method customize_themes_print_templates
 * @method dashboard_browser_nag_class
 * @method date_i18n
 * @method dbdelta
 * @method deactivate_plugins
 * @method deactivate_sitewide_plugin
 * @method dead_db
 * @method debug_fclose
 * @method debug_fopen
 * @method debug_fwrite
 * @method default_password_nag
 * @method default_password_nag_edit_user
 * @method default_password_nag_handler
 * @method default_topic_count_scale
 * @method default_topic_count_text
 * @method delete_all_user_settings
 * @method delete_blog_option
 * @method delete_comment_meta
 * @method delete_get_calendar_cache
 * @method delete_meta
 * @method delete_metadata
 * @method delete_metadata_by_mid
 * @method delete_network_option
 * @method delete_option
 * @method delete_plugins
 * @method delete_post_meta
 * @method delete_post_meta_by_key
 * @method delete_post_thumbnail
 * @method delete_site_option
 * @method delete_site_transient
 * @method delete_term_meta
 * @method delete_theme
 * @method delete_transient
 * @method delete_user_meta
 * @method delete_user_option
 * @method delete_user_setting
 * @method delete_usermeta
 * @method delete_users_add_js
 * @method deslash
 * @method did_action
 * @method disabled
 * @method discover_pingback_server_uri
 * @method dismiss_core_update
 * @method dismissed_updates
 * @method display_header
 * @method display_header_text
 * @method display_plugins_table
 * @method display_setup_form
 * @method display_space_usage
 * @method display_theme
 * @method display_themes
 * @method do_accordion_sections
 * @method do_action
 * @method do_action_deprecated
 * @method do_action_ref_array
 * @method do_activate_header
 * @method do_all_pings
 * @method do_core_upgrade
 * @method do_dismiss_core_update
 * @method do_enclose
 * @method do_feed
 * @method do_feed_atom
 * @method do_feed_rdf
 * @method do_feed_rss
 * @method do_feed_rss2
 * @method do_meta_boxes
 * @method do_robots
 * @method do_settings_fields
 * @method do_settings_sections
 * @method do_shortcode
 * @method do_shortcode_tag
 * @method do_shortcodes_in_html_tags
 * @method do_signup_header
 * @method do_trackbacks
 * @method do_undismiss_core_update
 * @method documentation_link
 * @method doing_action
 * @method doing_filter
 * @method domain_exists
 * @method download_url
 * @method drop_index
 * @method dropdown_categories
 * @method dropdown_cats
 * @method dropdown_link_categories
 * @method dynamic_sidebar
 * @method edit_bookmark_link
 * @method edit_comment
 * @method edit_comment_link
 * @method edit_form_image_editor
 * @method edit_link
 * @method edit_post
 * @method edit_post_link
 * @method edit_tag_link
 * @method edit_term_link
 * @method edit_user
 * @method email_exists
 * @method endelement
 * @method enqueue_comment_hotkeys_js
 * @method enqueue_embed_scripts
 * @method ent2ncr
 * @method esc_attr
 * @method esc_attr__
 * @method esc_attr_e
 * @method esc_attr_x
 * @method esc_html
 * @method esc_html__
 * @method esc_html_e
 * @method esc_html_x
 * @method esc_js
 * @method esc_sql
 * @method esc_textarea
 * @method esc_url
 * @method esc_url_raw
 * @method export_add_js
 * @method export_date_options
 * @method export_wp
 * @method extract_from_markers
 * @method favorite_actions
 * @method feed_content_type
 * @method feed_links
 * @method feed_links_extra
 * @method fetch_feed
 * @method fetch_rss
 * @method file_is_displayable_image
 * @method file_is_valid_image
 * @method filter_ssl
 * @method find_core_auto_update
 * @method find_core_update
 * @method find_posts_div
 * @method fix_import_form_size
 * @method fix_phpmailer_messageid
 * @method floated_admin_avatar
 * @method flush_rewrite_rules
 * @method force_balance_tags
 * @method force_ssl_admin
 * @method force_ssl_content
 * @method force_ssl_login
 * @method form_option
 * @method format_code_lang
 * @method format_for_editor
 * @method format_to_edit
 * @method format_to_post
 * @method funky_javascript_callback
 * @method funky_javascript_fix
 * @method gallery_shortcode
 * @method gd_edit_image_support
 * @method generate_random_password
 * @method generic_ping
 * @method get_404_template
 * @method get_active_blog_for_user
 * @method get_adjacent_post
 * @method get_adjacent_post_link
 * @method get_adjacent_post_rel_link
 * @method get_admin_page_parent
 * @method get_admin_page_title
 * @method get_admin_url
 * @method get_admin_users_for_domain
 * @method get_all_category_ids
 * @method get_all_page_ids
 * @method get_all_post_type_supports
 * @method get_all_user_settings
 * @method get_alloptions
 * @method get_alloptions_110
 * @method get_allowed_http_origins
 * @method get_allowed_mime_types
 * @method get_allowed_themes
 * @method get_ancestors
 * @method get_approved_comments
 * @method get_archive_template
 * @method get_archives
 * @method get_archives_link
 * @method get_attached_file
 * @method get_attached_media
 * @method get_attachment_fields_to_edit
 * @method get_attachment_icon
 * @method get_attachment_icon_src
 * @method get_attachment_innerhtml
 * @method get_attachment_link
 * @method get_attachment_taxonomies
 * @method get_attachment_template
 * @method get_author_feed_link
 * @method get_author_link
 * @method get_author_name
 * @method get_author_posts_url
 * @method get_author_rss_link
 * @method get_author_template
 * @method get_author_user_ids
 * @method get_autotoggle
 * @method get_available_languages
 * @method get_available_post_mime_types
 * @method get_available_post_statuses
 * @method get_avatar
 * @method get_avatar_data
 * @method get_avatar_url
 * @method get_background_color
 * @method get_background_image
 * @method get_blog_count
 * @method get_blog_details
 * @method get_blog_id_from_url
 * @method get_blog_list
 * @method get_blog_option
 * @method get_blog_permalink
 * @method get_blog_post
 * @method get_blog_status
 * @method get_blogaddress_by_domain
 * @method get_blogaddress_by_id
 * @method get_blogaddress_by_name
 * @method get_bloginfo
 * @method get_bloginfo_rss
 * @method get_blogs_of_user
 * @method get_body_class
 * @method get_bookmark
 * @method get_bookmark_field
 * @method get_bookmarks
 * @method get_boundary_post
 * @method get_boundary_post_rel_link
 * @method get_broken_themes
 * @method get_calendar
 * @method get_cancel_comment_reply_link
 * @method get_cat_id
 * @method get_cat_name
 * @method get_categories
 * @method get_category
 * @method get_category_by_path
 * @method get_category_by_slug
 * @method get_category_children
 * @method get_category_feed_link
 * @method get_category_link
 * @method get_category_parents
 * @method get_category_rss_link
 * @method get_category_template
 * @method get_category_to_edit
 * @method get_catname
 * @method get_children
 * @method get_clean_basedomain
 * @method get_cli_args
 * @method get_column_headers
 * @method get_comment
 * @method get_comment_author
 * @method get_comment_author_email
 * @method get_comment_author_email_link
 * @method get_comment_author_ip
 * @method get_comment_author_link
 * @method get_comment_author_rss
 * @method get_comment_author_url
 * @method get_comment_author_url_link
 * @method get_comment_class
 * @method get_comment_count
 * @method get_comment_date
 * @method get_comment_excerpt
 * @method get_comment_guid
 * @method get_comment_id
 * @method get_comment_id_fields
 * @method get_comment_link
 * @method get_comment_meta
 * @method get_comment_pages_count
 * @method get_comment_reply_link
 * @method get_comment_statuses
 * @method get_comment_text
 * @method get_comment_time
 * @method get_comment_to_edit
 * @method get_comment_type
 * @method get_commentdata
 * @method get_comments
 * @method get_comments_link
 * @method get_comments_number
 * @method get_comments_number_text
 * @method get_comments_pagenum_link
 * @method get_comments_popup_template
 * @method get_compat_media_markup
 * @method get_core_checksums
 * @method get_core_updates
 * @method get_current_blog_id
 * @method get_current_network_id
 * @method get_current_screen
 * @method get_current_site
 * @method get_current_site_name
 * @method get_current_theme
 * @method get_current_user_id
 * @method get_currentuserinfo
 * @method get_custom_header
 * @method get_custom_logo
 * @method get_dashboard_blog
 * @method get_dashboard_url
 * @method get_date_from_gmt
 * @method get_date_template
 * @method get_day_link
 * @method get_default_comment_status
 * @method get_default_feed
 * @method get_default_link_to_edit
 * @method get_default_page_to_edit
 * @method get_default_post_to_edit
 * @method get_delete_post_link
 * @method get_dirsize
 * @method get_dropins
 * @method get_edit_bookmark_link
 * @method get_edit_comment_link
 * @method get_edit_post_link
 * @method get_edit_profile_url
 * @method get_edit_tag_link
 * @method get_edit_term_link
 * @method get_edit_user_link
 * @method get_editable_authors
 * @method get_editable_roles
 * @method get_editable_user_ids
 * @method get_editor_stylesheets
 * @method get_embed_template
 * @method get_enclosed
 * @method get_extended
 * @method get_feed_link
 * @method get_file_data
 * @method get_file_description
 * @method get_filesystem_method
 * @method get_footer
 * @method get_front_page_template
 * @method get_gmt_from_date
 * @method get_header
 * @method get_header_image
 * @method get_header_image_tag
 * @method get_header_textcolor
 * @method get_hidden_columns
 * @method get_hidden_meta_boxes
 * @method get_home_path
 * @method get_home_template
 * @method get_home_url
 * @method get_html_split_regex
 * @method get_http_origin
 * @method get_id_from_blogname
 * @method get_image_send_to_editor
 * @method get_image_tag
 * @method get_importers
 * @method get_index_rel_link
 * @method get_index_template
 * @method get_inline_data
 * @method get_intermediate_image_sizes
 * @method get_language_attributes
 * @method get_last_updated
 * @method get_lastcommentmodified
 * @method get_lastpostdate
 * @method get_lastpostmodified
 * @method get_link
 * @method get_link_to_edit
 * @method get_linkcatname
 * @method get_linkobjects
 * @method get_linkobjectsbyname
 * @method get_linkrating
 * @method get_links
 * @method get_links_list
 * @method get_links_withrating
 * @method get_linksbyname
 * @method get_linksbyname_withrating
 * @method get_locale
 * @method get_locale_stylesheet_uri
 * @method get_main_network_id
 * @method get_media_embedded_in_content
 * @method get_media_item
 * @method get_media_items
 * @method get_meta_keys
 * @method get_meta_sql
 * @method get_metadata
 * @method get_metadata_by_mid
 * @method get_month_link
 * @method get_most_active_blogs
 * @method get_most_recent_post_of_user
 * @method get_mu_plugins
 * @method get_nav_menu_locations
 * @method get_network
 * @method get_network_by_path
 * @method get_network_option
 * @method get_networks
 * @method get_next_comments_link
 * @method get_next_post
 * @method get_next_post_link
 * @method get_next_posts_link
 * @method get_next_posts_page_link
 * @method get_nonauthor_user_ids
 * @method get_num_queries
 * @method get_object_taxonomies
 * @method get_object_term_cache
 * @method get_objects_in_term
 * @method get_oembed_endpoint_url
 * @method get_oembed_response_data
 * @method get_oembed_response_data_rich
 * @method get_option
 * @method get_others_drafts
 * @method get_others_pending
 * @method get_others_unpublished_posts
 * @method get_page
 * @method get_page_by_path
 * @method get_page_by_title
 * @method get_page_children
 * @method get_page_hierarchy
 * @method get_page_link
 * @method get_page_of_comment
 * @method get_page_statuses
 * @method get_page_template
 * @method get_page_template_slug
 * @method get_page_templates
 * @method get_page_uri
 * @method get_paged_template
 * @method get_pagenum_link
 * @method get_pages
 * @method get_parent_post_rel_link
 * @method get_password_reset_key
 * @method get_pending_comments_num
 * @method get_permalink
 * @method get_plugin_data
 * @method get_plugin_files
 * @method get_plugin_page_hook
 * @method get_plugin_page_hookname
 * @method get_plugin_updates
 * @method get_plugins
 * @method get_post
 * @method get_post_ancestors
 * @method get_post_class
 * @method get_post_comments_feed_link
 * @method get_post_custom
 * @method get_post_custom_keys
 * @method get_post_custom_values
 * @method get_post_embed_html
 * @method get_post_embed_url
 * @method get_post_field
 * @method get_post_format
 * @method get_post_format_link
 * @method get_post_format_slugs
 * @method get_post_format_string
 * @method get_post_format_strings
 * @method get_post_galleries
 * @method get_post_galleries_images
 * @method get_post_gallery
 * @method get_post_gallery_images
 * @method get_post_meta
 * @method get_post_meta_by_id
 * @method get_post_mime_type
 * @method get_post_mime_types
 * @method get_post_modified_time
 * @method get_post_permalink
 * @method get_post_reply_link
 * @method get_post_stati
 * @method get_post_status
 * @method get_post_status_object
 * @method get_post_statuses
 * @method get_post_taxonomies
 * @method get_post_thumbnail_id
 * @method get_post_time
 * @method get_post_to_edit
 * @method get_post_type
 * @method get_post_type_archive_feed_link
 * @method get_post_type_archive_link
 * @method get_post_type_archive_template
 * @method get_post_type_capabilities
 * @method get_post_type_labels
 * @method get_post_type_object
 * @method get_post_types
 * @method get_post_types_by_support
 * @method get_postdata
 * @method get_posts
 * @method get_posts_by_author_sql
 * @method get_posts_nav_link
 * @method get_preferred_from_update_core
 * @method get_preview_post_link
 * @method get_previous_comments_link
 * @method get_previous_post
 * @method get_previous_post_link
 * @method get_previous_posts_link
 * @method get_previous_posts_page_link
 * @method get_private_posts_cap_sql
 * @method get_profile
 * @method get_pung
 * @method get_queried_object
 * @method get_queried_object_id
 * @method get_query_template
 * @method get_query_var
 * @method get_random_header_image
 * @method get_raw_theme_root
 * @method get_real_file_to_edit
 * @method get_registered_meta_keys
 * @method get_registered_metadata
 * @method get_registered_nav_menus
 * @method get_rest_url
 * @method get_role
 * @method get_rss
 * @method get_sample_permalink
 * @method get_sample_permalink_html
 * @method get_screen_icon
 * @method get_search_comments_feed_link
 * @method get_search_feed_link
 * @method get_search_form
 * @method get_search_link
 * @method get_search_query
 * @method get_search_template
 * @method get_settings
 * @method get_settings_errors
 * @method get_shortcode_atts_regex
 * @method get_shortcode_regex
 * @method get_shortcut_link
 * @method get_sidebar
 * @method get_single_template
 * @method get_singular_template
 * @method get_site
 * @method get_site_allowed_themes
 * @method get_site_by_path
 * @method get_site_icon_url
 * @method get_site_option
 * @method get_site_transient
 * @method get_site_url
 * @method get_sites
 * @method get_sitestats
 * @method get_space_allowed
 * @method get_space_used
 * @method get_status_header_desc
 * @method get_stylesheet
 * @method get_stylesheet_directory
 * @method get_stylesheet_directory_uri
 * @method get_stylesheet_uri
 * @method get_subdirectory_reserved_names
 * @method get_submit_button
 * @method get_super_admins
 * @method get_tag
 * @method get_tag_feed_link
 * @method get_tag_link
 * @method get_tag_regex
 * @method get_tag_template
 * @method get_tags
 * @method get_tags_to_edit
 * @method get_tax_sql
 * @method get_taxonomies
 * @method get_taxonomies_for_attachments
 * @method get_taxonomy
 * @method get_taxonomy_labels
 * @method get_taxonomy_template
 * @method get_temp_dir
 * @method get_template
 * @method get_template_directory
 * @method get_template_directory_uri
 * @method get_template_part
 * @method get_term
 * @method get_term_by
 * @method get_term_children
 * @method get_term_feed_link
 * @method get_term_field
 * @method get_term_link
 * @method get_term_meta
 * @method get_term_to_edit
 * @method get_terms
 * @method get_terms_to_edit
 * @method get_the_archive_description
 * @method get_the_archive_title
 * @method get_the_attachment_link
 * @method get_the_author
 * @method get_the_author_aim
 * @method get_the_author_description
 * @method get_the_author_email
 * @method get_the_author_firstname
 * @method get_the_author_icq
 * @method get_the_author_id
 * @method get_the_author_lastname
 * @method get_the_author_link
 * @method get_the_author_login
 * @method get_the_author_meta
 * @method get_the_author_msn
 * @method get_the_author_nickname
 * @method get_the_author_posts
 * @method get_the_author_posts_link
 * @method get_the_author_url
 * @method get_the_author_yim
 * @method get_the_category
 * @method get_the_category_by_id
 * @method get_the_category_list
 * @method get_the_category_rss
 * @method get_the_comments_navigation
 * @method get_the_comments_pagination
 * @method get_the_content
 * @method get_the_content_feed
 * @method get_the_date
 * @method get_the_excerpt
 * @method get_the_generator
 * @method get_the_guid
 * @method get_the_id
 * @method get_the_modified_author
 * @method get_the_modified_date
 * @method get_the_modified_time
 * @method get_the_password_form
 * @method get_the_permalink
 * @method get_the_post_navigation
 * @method get_the_post_thumbnail
 * @method get_the_post_thumbnail_caption
 * @method get_the_post_thumbnail_url
 * @method get_the_posts_navigation
 * @method get_the_posts_pagination
 * @method get_the_tag_list
 * @method get_the_tags
 * @method get_the_taxonomies
 * @method get_the_term_list
 * @method get_the_terms
 * @method get_the_time
 * @method get_the_title
 * @method get_the_title_rss
 * @method get_theme
 * @method get_theme_data
 * @method get_theme_feature_list
 * @method get_theme_mod
 * @method get_theme_mods
 * @method get_theme_root
 * @method get_theme_root_uri
 * @method get_theme_roots
 * @method get_theme_support
 * @method get_theme_update_available
 * @method get_theme_updates
 * @method get_themes
 * @method get_to_ping
 * @method get_trackback_url
 * @method get_transient
 * @method get_translations_for_domain
 * @method get_udims
 * @method get_upload_iframe_src
 * @method get_upload_space_available
 * @method get_uploaded_header_images
 * @method get_url_in_content
 * @method get_user_by
 * @method get_user_by_email
 * @method get_user_count
 * @method get_user_details
 * @method get_user_id_from_string
 * @method get_user_meta
 * @method get_user_metavalues
 * @method get_user_option
 * @method get_user_setting
 * @method get_user_to_edit
 * @method get_userdata
 * @method get_userdatabylogin
 * @method get_usermeta
 * @method get_usernumposts
 * @method get_users
 * @method get_users_drafts
 * @method get_users_of_blog
 * @method get_weekstartend
 * @method get_wp_title_rss
 * @method get_year_link
 * @method global_terms
 * @method global_terms_enabled
 * @method got_mod_rewrite
 * @method got_url_rewrite
 * @method graceful_fail
 * @method grant_super_admin
 * @method gzip_compression
 * @method has_action
 * @method has_category
 * @method has_custom_logo
 * @method has_excerpt
 * @method has_filter
 * @method has_header_image
 * @method has_image_size
 * @method has_meta
 * @method has_nav_menu
 * @method has_post_format
 * @method has_post_thumbnail
 * @method has_shortcode
 * @method has_site_icon
 * @method has_tag
 * @method has_term
 * @method hash_equals
 * @method have_comments
 * @method have_posts
 * @method header_image
 * @method header_textcolor
 * @method heartbeat_autosave
 * @method home_url
 * @method html_type_rss
 * @method htmlentities2
 * @method human_time_diff
 * @method iframe_footer
 * @method iframe_header
 * @method iis7_add_rewrite_rule
 * @method iis7_delete_rewrite_rule
 * @method iis7_rewrite_rule_exists
 * @method iis7_save_url_rewrite_rules
 * @method iis7_supports_permalinks
 * @method image_add_caption
 * @method image_align_input_fields
 * @method image_attachment_fields_to_edit
 * @method image_attachment_fields_to_save
 * @method image_constrain_size_for_editor
 * @method image_downsize
 * @method image_edit_apply_changes
 * @method image_get_intermediate_size
 * @method image_hwstring
 * @method image_link_input_fields
 * @method image_make_intermediate_size
 * @method image_media_send_to_editor
 * @method image_resize
 * @method image_resize_dimensions
 * @method image_size_input_fields
 * @method img_caption_shortcode
 * @method in_category
 * @method in_the_loop
 * @method includes_url
 * @method index_rel_link
 * @method insert_blog
 * @method insert_with_markers
 * @method install_blog
 * @method install_blog_defaults
 * @method install_dashboard
 * @method install_global_terms
 * @method install_network
 * @method install_plugin_information
 * @method install_plugin_install_status
 * @method install_plugins_favorites_form
 * @method install_plugins_upload
 * @method install_popular_tags
 * @method install_search_form
 * @method install_theme_information
 * @method install_theme_search_form
 * @method install_themes_dashboard
 * @method install_themes_feature_list
 * @method install_themes_upload
 * @method is_404
 * @method is_active_sidebar
 * @method is_active_widget
 * @method is_admin
 * @method is_admin_bar_showing
 * @method is_allowed_http_origin
 * @method is_archive
 * @method is_archived
 * @method is_attachment
 * @method is_author
 * @method is_blog_admin
 * @method is_blog_installed
 * @method is_blog_user
 * @method is_category
 * @method is_child_theme
 * @method is_client_error
 * @method is_comment_feed
 * @method is_comments_popup
 * @method is_customize_preview
 * @method is_date
 * @method is_day
 * @method is_dynamic_sidebar
 * @method is_email
 * @method is_email_address_unsafe
 * @method is_embed
 * @method is_error
 * @method is_feed
 * @method is_front_page
 * @method is_home
 * @method is_info
 * @method is_lighttpd_before_150
 * @method is_local_attachment
 * @method is_main_blog
 * @method is_main_network
 * @method is_main_query
 * @method is_main_site
 * @method is_month
 * @method is_multi_author
 * @method is_multisite
 * @method is_nav_menu
 * @method is_nav_menu_item
 * @method is_network_admin
 * @method is_network_only_plugin
 * @method is_new_day
 * @method is_object_in_taxonomy
 * @method is_object_in_term
 * @method is_page
 * @method is_page_template
 * @method is_paged
 * @method is_plugin_active
 * @method is_plugin_active_for_network
 * @method is_plugin_inactive
 * @method is_plugin_page
 * @method is_post_type_archive
 * @method is_post_type_hierarchical
 * @method is_post_type_viewable
 * @method is_preview
 * @method is_protected_meta
 * @method is_random_header_image
 * @method is_redirect
 * @method is_registered_sidebar
 * @method is_robots
 * @method is_rtl
 * @method is_search
 * @method is_serialized
 * @method is_serialized_string
 * @method is_server_error
 * @method is_single
 * @method is_singular
 * @method is_site_admin
 * @method is_ssl
 * @method is_sticky
 * @method is_subdomain_install
 * @method is_success
 * @method is_super_admin
 * @method is_tag
 * @method is_tax
 * @method is_taxonomy
 * @method is_taxonomy_hierarchical
 * @method is_term
 * @method is_textdomain_loaded
 * @method is_time
 * @method is_trackback
 * @method is_uninstallable_plugin
 * @method is_upload_space_available
 * @method is_user_admin
 * @method is_user_logged_in
 * @method is_user_member_of_blog
 * @method is_user_option_local
 * @method is_user_spammy
 * @method is_wp_error
 * @method is_wpmu_sitewide_plugin
 * @method is_year
 * @method iso8601_timezone_to_offset
 * @method iso8601_to_datetime
 * @method js_escape
 * @method json_last_error_msg
 * @method kses_init
 * @method kses_init_filters
 * @method kses_remove_filters
 * @method language_attributes
 * @method like_escape
 * @method link_advanced_meta_box
 * @method link_categories_meta_box
 * @method link_pages
 * @method link_submit_meta_box
 * @method link_target_meta_box
 * @method link_xfn_meta_box
 * @method links_add_base_url
 * @method links_add_target
 * @method links_popup_script
 * @method list_authors
 * @method list_cats
 * @method list_core_update
 * @method list_files
 * @method list_meta
 * @method list_plugin_updates
 * @method list_theme_updates
 * @method list_translation_updates
 * @method load_child_theme_textdomain
 * @method load_default_textdomain
 * @method load_image_to_edit
 * @method load_muplugin_textdomain
 * @method load_plugin_textdomain
 * @method load_template
 * @method load_textdomain
 * @method load_theme_textdomain
 * @method locale_stylesheet
 * @method locate_template
 * @method login_footer
 * @method login_header
 * @method logio
 * @method maintenance_nag
 * @method make_clickable
 * @method make_db_current
 * @method make_db_current_silent
 * @method make_site_theme
 * @method make_site_theme_from_default
 * @method make_site_theme_from_oldschool
 * @method make_url_footnote
 * @method map_deep
 * @method map_meta_cap
 * @method maybe_add_column
 * @method maybe_add_existing_user_to_blog
 * @method maybe_convert_table_to_utf8mb4
 * @method maybe_create_table
 * @method maybe_disable_automattic_widgets
 * @method maybe_disable_link_manager
 * @method maybe_drop_column
 * @method maybe_hash_hex_color
 * @method maybe_redirect_404
 * @method maybe_serialize
 * @method maybe_unserialize
 * @method mb_strlen
 * @method mbstring_binary_safe_encoding
 * @method media_buttons
 * @method media_handle_sideload
 * @method media_handle_upload
 * @method media_post_single_attachment_fields_to_edit
 * @method media_send_to_editor
 * @method media_sideload_image
 * @method media_single_attachment_fields_to_edit
 * @method media_upload_audio
 * @method media_upload_file
 * @method media_upload_flash_bypass
 * @method media_upload_form
 * @method media_upload_form_handler
 * @method media_upload_gallery
 * @method media_upload_gallery_form
 * @method media_upload_header
 * @method media_upload_html_bypass
 * @method media_upload_image
 * @method media_upload_library
 * @method media_upload_library_form
 * @method media_upload_max_image_resize
 * @method media_upload_tabs
 * @method media_upload_text_after
 * @method media_upload_type_form
 * @method media_upload_type_url_form
 * @method media_upload_video
 * @method menu_page_url
 * @method meta_box_prefs
 * @method meta_form
 * @method metadata_exists
 * @method ms_allowed_http_request_hosts
 * @method ms_cookie_constants
 * @method ms_deprecated_blogs_file
 * @method ms_file_constants
 * @method ms_is_switched
 * @method ms_load_current_site_and_network
 * @method ms_not_installed
 * @method ms_site_check
 * @method ms_subdomain_constants
 * @method ms_upload_constants
 * @method mu_dropdown_languages
 * @method mu_options
 * @method multisite_over_quota_message
 * @method mysql2date
 * @method mysql_to_rfc3339
 * @method network_admin_url
 * @method network_domain_check
 * @method network_edit_site_nav
 * @method network_home_url
 * @method network_settings_add_js
 * @method network_site_url
 * @method network_step1
 * @method network_step2
 * @method new_user_email_admin_notice
 * @method newblog_notify_siteadmin
 * @method newuser_notify_siteadmin
 * @method next_comments_link
 * @method next_image_link
 * @method next_post
 * @method next_post_link
 * @method next_post_rel_link
 * @method next_posts
 * @method next_posts_link
 * @method next_widget_id_number
 * @method nocache_headers
 * @method noindex
 * @method normalize_whitespace
 * @method number_format_i18n
 * @method option_update_filter
 * @method options_discussion_add_js
 * @method options_general_add_js
 * @method options_permalink_add_js
 * @method options_reading_add_js
 * @method options_reading_blog_charset
 * @method page_attributes_meta_box
 * @method page_template_dropdown
 * @method paginate_comments_links
 * @method paginate_links
 * @method parent_dropdown
 * @method parent_post_rel_link
 * @method parse_w3cdtf
 * @method path_is_absolute
 * @method path_join
 * @method pclziputilcopyblock
 * @method pclziputiloptiontext
 * @method pclziputilpathinclusion
 * @method pclziputilpathreduction
 * @method pclziputilrename
 * @method pclziputiltranslatewinpath
 * @method permalink_anchor
 * @method permalink_link
 * @method permalink_single_rss
 * @method pingback
 * @method pingback_ping_source_uri
 * @method pings_open
 * @method plugin_basename
 * @method plugin_dir_path
 * @method plugin_dir_url
 * @method plugin_sandbox_scrape
 * @method plugins_api
 * @method plugins_url
 * @method populate_network
 * @method populate_options
 * @method populate_roles
 * @method populate_roles_160
 * @method populate_roles_210
 * @method populate_roles_230
 * @method populate_roles_250
 * @method populate_roles_260
 * @method populate_roles_270
 * @method populate_roles_280
 * @method populate_roles_300
 * @method popuplinks
 * @method post_author_meta_box
 * @method post_categories_meta_box
 * @method post_class
 * @method post_comment_meta_box
 * @method post_comment_meta_box_thead
 * @method post_comment_status_meta_box
 * @method post_comments_feed_link
 * @method post_custom
 * @method post_custom_meta_box
 * @method post_excerpt_meta_box
 * @method post_exists
 * @method post_form_autocomplete_off
 * @method post_format_meta_box
 * @method post_password_required
 * @method post_permalink
 * @method post_preview
 * @method post_reply_link
 * @method post_revisions_meta_box
 * @method post_slug_meta_box
 * @method post_submit_meta_box
 * @method post_tags_meta_box
 * @method post_thumbnail_meta_box
 * @method post_trackback_meta_box
 * @method post_type_archive_title
 * @method post_type_exists
 * @method post_type_supports
 * @method postbox_classes
 * @method posts_nav_link
 * @method pre_schema_upgrade
 * @method prep_atom_text_construct
 * @method prepend_attachment
 * @method prev_post_rel_link
 * @method preview_theme
 * @method preview_theme_ob_filter
 * @method preview_theme_ob_filter_callback
 * @method previous_comments_link
 * @method previous_image_link
 * @method previous_post
 * @method previous_post_link
 * @method previous_posts
 * @method previous_posts_link
 * @method print_admin_styles
 * @method print_column_headers
 * @method print_embed_comments_button
 * @method print_embed_scripts
 * @method print_embed_sharing_button
 * @method print_embed_sharing_dialog
 * @method print_embed_styles
 * @method print_emoji_detection_script
 * @method print_emoji_styles
 * @method print_footer_scripts
 * @method print_head_scripts
 * @method print_late_styles
 * @method privacy_ping_filter
 * @method query_posts
 * @method random_bytes
 * @method random_int
 * @method randomcompat_intval
 * @method randomcompat_strlen
 * @method randomcompat_substr
 * @method rawurlencode_deep
 * @method recurse_dirsize
 * @method redirect_canonical
 * @method redirect_guess_404_permalink
 * @method redirect_post
 * @method redirect_this_site
 * @method refresh_blog_details
 * @method refresh_user_details
 * @method register_activation_hook
 * @method register_admin_color_schemes
 * @method register_column_headers
 * @method register_deactivation_hook
 * @method register_default_headers
 * @method register_importer
 * @method register_meta
 * @method register_nav_menu
 * @method register_nav_menus
 * @method register_new_user
 * @method register_post_status
 * @method register_post_type
 * @method register_rest_route
 * @method register_setting
 * @method register_sidebar
 * @method register_sidebar_widget
 * @method register_sidebars
 * @method register_taxonomy
 * @method register_taxonomy_for_object_type
 * @method register_theme_directory
 * @method register_uninstall_hook
 * @method register_widget
 * @method register_widget_control
 * @method registered_meta_key_exists
 * @method rel_canonical
 * @method remove_accents
 * @method remove_action
 * @method remove_all_actions
 * @method remove_all_filters
 * @method remove_all_shortcodes
 * @method remove_custom_background
 * @method remove_custom_image_header
 * @method remove_editor_styles
 * @method remove_filter
 * @method remove_image_size
 * @method remove_menu_page
 * @method remove_meta_box
 * @method remove_option_update_handler
 * @method remove_option_whitelist
 * @method remove_permastruct
 * @method remove_post_type_support
 * @method remove_query_arg
 * @method remove_rewrite_tag
 * @method remove_role
 * @method remove_shortcode
 * @method remove_submenu_page
 * @method remove_theme_mod
 * @method remove_theme_mods
 * @method remove_theme_support
 * @method remove_user_from_blog
 * @method request_filesystem_credentials
 * @method require_if_theme_supports
 * @method require_wp_db
 * @method reset_mbstring_encoding
 * @method reset_password
 * @method rest_api_default_filters
 * @method rest_api_init
 * @method rest_api_loaded
 * @method rest_api_register_rewrites
 * @method rest_cookie_check_errors
 * @method rest_cookie_collect_status
 * @method rest_do_request
 * @method rest_ensure_request
 * @method rest_ensure_response
 * @method rest_get_date_with_gmt
 * @method rest_get_server
 * @method rest_get_url_prefix
 * @method rest_handle_deprecated_argument
 * @method rest_handle_deprecated_function
 * @method rest_handle_options_request
 * @method rest_output_link_header
 * @method rest_output_link_wp_head
 * @method rest_output_rsd
 * @method rest_parse_date
 * @method rest_send_allow_header
 * @method rest_send_cors_headers
 * @method rest_url
 * @method restore_current_blog
 * @method retrieve_password
 * @method retrieve_widgets
 * @method revoke_super_admin
 * @method rewind_posts
 * @method rich_edit_exists
 * @method rsd_link
 * @method rss2_site_icon
 * @method rss_enclosure
 * @method safecss_filter_attr
 * @method sanitize_bookmark
 * @method sanitize_bookmark_field
 * @method sanitize_category
 * @method sanitize_category_field
 * @method sanitize_comment_cookies
 * @method sanitize_email
 * @method sanitize_file_name
 * @method sanitize_hex_color
 * @method sanitize_hex_color_no_hash
 * @method sanitize_html_class
 * @method sanitize_key
 * @method sanitize_meta
 * @method sanitize_mime_type
 * @method sanitize_option
 * @method sanitize_post
 * @method sanitize_post_field
 * @method sanitize_sql_orderby
 * @method sanitize_term
 * @method sanitize_term_field
 * @method sanitize_text_field
 * @method sanitize_title
 * @method sanitize_title_for_query
 * @method sanitize_title_with_dashes
 * @method sanitize_trackback_urls
 * @method sanitize_url
 * @method sanitize_user
 * @method sanitize_user_field
 * @method sanitize_user_object
 * @method save_mod_rewrite_rules
 * @method savedomdocument
 * @method screen_icon
 * @method screen_layout
 * @method screen_meta
 * @method screen_options
 * @method script_concat_settings
 * @method search_theme_directories
 * @method seems_utf8
 * @method selected
 * @method self_admin_url
 * @method self_link
 * @method send_confirmation_on_profile_email
 * @method send_frame_options_header
 * @method send_nosniff_header
 * @method send_origin_headers
 * @method separate_comments
 * @method set_current_screen
 * @method set_current_user
 * @method set_post_format
 * @method set_post_thumbnail
 * @method set_post_thumbnail_size
 * @method set_post_type
 * @method set_query_var
 * @method set_screen_options
 * @method set_site_transient
 * @method set_theme_mod
 * @method set_transient
 * @method set_url_scheme
 * @method set_user_setting
 * @method settings_errors
 * @method settings_fields
 * @method setup_config_display_header
 * @method setup_postdata
 * @method setup_userdata
 * @method shortcode_atts
 * @method shortcode_exists
 * @method shortcode_parse_atts
 * @method shortcode_unautop
 * @method show_admin_bar
 * @method show_blog_form
 * @method show_message
 * @method show_user_form
 * @method shutdown_action_hook
 * @method signup_another_blog
 * @method signup_blog
 * @method signup_get_available_languages
 * @method signup_nonce_check
 * @method signup_nonce_fields
 * @method signup_user
 * @method single_cat_title
 * @method single_month_title
 * @method single_post_title
 * @method single_tag_title
 * @method single_term_title
 * @method site_admin_notice
 * @method site_icon_url
 * @method site_url
 * @method size_format
 * @method smilies_init
 * @method sort_menu
 * @method spawn_cron
 * @method spl_autoload_functions
 * @method spl_autoload_register
 * @method spl_autoload_unregister
 * @method start_post_rel_link
 * @method start_wp
 * @method startelement
 * @method status_header
 * @method stick_post
 * @method sticky_class
 * @method stream_preview_image
 * @method strip_fragment_from_url
 * @method strip_shortcode_tag
 * @method strip_shortcodes
 * @method stripslashes_deep
 * @method stripslashes_from_strings_only
 * @method submit_button
 * @method switch_theme
 * @method switch_to_blog
 * @method sync_category_tag_slugs
 * @method tag_description
 * @method tag_escape
 * @method tag_exists
 * @method taxonomy_exists
 * @method term_description
 * @method term_exists
 * @method term_is_ancestor_of
 * @method the_archive_description
 * @method the_archive_title
 * @method the_attachment_link
 * @method the_attachment_links
 * @method the_author
 * @method the_author_aim
 * @method the_author_description
 * @method the_author_email
 * @method the_author_firstname
 * @method the_author_icq
 * @method the_author_id
 * @method the_author_lastname
 * @method the_author_link
 * @method the_author_login
 * @method the_author_meta
 * @method the_author_msn
 * @method the_author_nickname
 * @method the_author_posts
 * @method the_author_posts_link
 * @method the_author_url
 * @method the_author_yim
 * @method the_category
 * @method the_category_head
 * @method the_category_id
 * @method the_category_rss
 * @method the_comment
 * @method the_comments_navigation
 * @method the_comments_pagination
 * @method the_content
 * @method the_content_feed
 * @method the_content_rss
 * @method the_custom_logo
 * @method the_date
 * @method the_date_xml
 * @method the_editor
 * @method the_embed_site_title
 * @method the_excerpt
 * @method the_excerpt_embed
 * @method the_excerpt_rss
 * @method the_feed_link
 * @method the_generator
 * @method the_guid
 * @method the_header_image_tag
 * @method the_id
 * @method the_media_upload_tabs
 * @method the_meta
 * @method the_modified_author
 * @method the_modified_date
 * @method the_modified_time
 * @method the_permalink
 * @method the_permalink_rss
 * @method the_post
 * @method the_post_navigation
 * @method the_post_password
 * @method the_post_thumbnail
 * @method the_post_thumbnail_caption
 * @method the_post_thumbnail_url
 * @method the_posts_navigation
 * @method the_posts_pagination
 * @method the_search_query
 * @method the_shortlink
 * @method the_tags
 * @method the_taxonomies
 * @method the_terms
 * @method the_time
 * @method the_title
 * @method the_title_attribute
 * @method the_title_rss
 * @method the_weekday
 * @method the_weekday_date
 * @method the_widget
 * @method theme_update_available
 * @method themes_api
 * @method timer_start
 * @method timer_stop
 * @method tinymce_include
 * @method touch_time
 * @method trackback
 * @method trackback_rdf
 * @method trackback_response
 * @method trackback_url
 * @method trackback_url_list
 * @method trailingslashit
 * @method translate
 * @method translate_level_to_role
 * @method translate_nooped_plural
 * @method translate_smiley
 * @method translate_user_role
 * @method translate_with_context
 * @method translate_with_gettext_context
 * @method translations_api
 * @method type_url_form_audio
 * @method type_url_form_file
 * @method type_url_form_image
 * @method type_url_form_video
 * @method undismiss_core_update
 * @method unescape_invalid_shortcodes
 * @method uninstall_plugin
 * @method unload_textdomain
 * @method unregister_default_headers
 * @method unregister_meta_key
 * @method unregister_nav_menu
 * @method unregister_post_type
 * @method unregister_setting
 * @method unregister_sidebar
 * @method unregister_sidebar_widget
 * @method unregister_taxonomy
 * @method unregister_taxonomy_for_object_type
 * @method unregister_widget
 * @method unregister_widget_control
 * @method unstick_post
 * @method untrailingslashit
 * @method unzip_file
 * @method update_archived
 * @method update_attached_file
 * @method update_blog_details
 * @method update_blog_option
 * @method update_blog_public
 * @method update_blog_status
 * @method update_category_cache
 * @method update_comment_cache
 * @method update_comment_meta
 * @method update_core
 * @method update_gallery_tab
 * @method update_home_siteurl
 * @method update_meta
 * @method update_meta_cache
 * @method update_metadata
 * @method update_metadata_by_mid
 * @method update_nag
 * @method update_network_cache
 * @method update_network_option
 * @method update_object_term_cache
 * @method update_option
 * @method update_option_new_admin_email
 * @method update_page_cache
 * @method update_post_cache
 * @method update_post_caches
 * @method update_post_meta
 * @method update_post_thumbnail_cache
 * @method update_postmeta_cache
 * @method update_posts_count
 * @method update_recently_edited
 * @method update_right_now_message
 * @method update_site_cache
 * @method update_site_option
 * @method update_term_cache
 * @method update_term_meta
 * @method update_termmeta_cache
 * @method update_user_caches
 * @method update_user_meta
 * @method update_user_option
 * @method update_user_status
 * @method update_usermeta
 * @method upgrade_100
 * @method upgrade_101
 * @method upgrade_110
 * @method upgrade_130
 * @method upgrade_160
 * @method upgrade_210
 * @method upgrade_230
 * @method upgrade_230_old_tables
 * @method upgrade_230_options_table
 * @method upgrade_250
 * @method upgrade_252
 * @method upgrade_260
 * @method upgrade_270
 * @method upgrade_280
 * @method upgrade_290
 * @method upgrade_300
 * @method upgrade_330
 * @method upgrade_340
 * @method upgrade_350
 * @method upgrade_370
 * @method upgrade_372
 * @method upgrade_380
 * @method upgrade_400
 * @method upgrade_420
 * @method upgrade_430
 * @method upgrade_430_fix_comments
 * @method upgrade_431
 * @method upgrade_440
 * @method upgrade_450
 * @method upgrade_460
 * @method upgrade_all
 * @method upgrade_network
 * @method upgrade_old_slugs
 * @method upload_is_file_too_big
 * @method upload_is_user_over_quota
 * @method upload_size_limit_filter
 * @method upload_space_setting
 * @method url_is_accessable_via_ssl
 * @method url_shorten
 * @method url_to_postid
 * @method urldecode_deep
 * @method urlencode_deep
 * @method use_codepress
 * @method use_ssl_preference
 * @method user_admin_url
 * @method user_can
 * @method user_can_access_admin_page
 * @method user_can_create_draft
 * @method user_can_create_post
 * @method user_can_delete_post
 * @method user_can_delete_post_comments
 * @method user_can_edit_post
 * @method user_can_edit_post_comments
 * @method user_can_edit_post_date
 * @method user_can_edit_user
 * @method user_can_richedit
 * @method user_can_set_post_date
 * @method user_pass_ok
 * @method user_trailingslashit
 * @method username_exists
 * @method users_can_register_signup_filter
 * @method utf8_uri_encode
 * @method valid_unicode
 * @method validate_active_plugins
 * @method validate_another_blog_signup
 * @method validate_blog_form
 * @method validate_blog_signup
 * @method validate_current_theme
 * @method validate_email
 * @method validate_file
 * @method validate_file_to_edit
 * @method validate_plugin
 * @method validate_user_form
 * @method validate_user_signup
 * @method validate_username
 * @method verify_file_md5
 * @method walk_category_dropdown_tree
 * @method walk_category_tree
 * @method walk_nav_menu_tree
 * @method walk_page_dropdown_tree
 * @method walk_page_tree
 * @method weblog_ping
 * @method welcome_user_msg_filter
 * @method win_is_writable
 * @method wlwmanifest_link
 * @method wp
 * @method wp_add_dashboard_widget
 * @method wp_add_id3_tag_data
 * @method wp_add_inline_script
 * @method wp_add_inline_style
 * @method wp_add_object_terms
 * @method wp_add_post_tags
 * @method wp_add_trashed_suffix_to_post_name_for_post
 * @method wp_add_trashed_suffix_to_post_name_for_trashed_posts
 * @method wp_admin_bar_add_secondary_groups
 * @method wp_admin_bar_appearance_menu
 * @method wp_admin_bar_comments_menu
 * @method wp_admin_bar_customize_menu
 * @method wp_admin_bar_dashboard_view_site_menu
 * @method wp_admin_bar_edit_menu
 * @method wp_admin_bar_header
 * @method wp_admin_bar_my_account_item
 * @method wp_admin_bar_my_account_menu
 * @method wp_admin_bar_my_sites_menu
 * @method wp_admin_bar_new_content_menu
 * @method wp_admin_bar_render
 * @method wp_admin_bar_search_menu
 * @method wp_admin_bar_shortlink_menu
 * @method wp_admin_bar_sidebar_toggle
 * @method wp_admin_bar_site_menu
 * @method wp_admin_bar_updates_menu
 * @method wp_admin_bar_wp_menu
 * @method wp_admin_canonical_url
 * @method wp_admin_css
 * @method wp_admin_css_color
 * @method wp_admin_css_uri
 * @method wp_ajax_add_link_category
 * @method wp_ajax_add_menu_item
 * @method wp_ajax_add_meta
 * @method wp_ajax_add_tag
 * @method wp_ajax_add_user
 * @method wp_ajax_ajax_tag_search
 * @method wp_ajax_autocomplete_user
 * @method wp_ajax_closed_postboxes
 * @method wp_ajax_crop_image
 * @method wp_ajax_dashboard_widgets
 * @method wp_ajax_date_format
 * @method wp_ajax_delete_comment
 * @method wp_ajax_delete_inactive_widgets
 * @method wp_ajax_delete_link
 * @method wp_ajax_delete_meta
 * @method wp_ajax_delete_page
 * @method wp_ajax_delete_plugin
 * @method wp_ajax_delete_post
 * @method wp_ajax_delete_tag
 * @method wp_ajax_delete_theme
 * @method wp_ajax_destroy_sessions
 * @method wp_ajax_dim_comment
 * @method wp_ajax_dismiss_wp_pointer
 * @method wp_ajax_edit_comment
 * @method wp_ajax_fetch_list
 * @method wp_ajax_find_posts
 * @method wp_ajax_generate_password
 * @method wp_ajax_get_attachment
 * @method wp_ajax_get_comments
 * @method wp_ajax_get_permalink
 * @method wp_ajax_get_revision_diffs
 * @method wp_ajax_get_tagcloud
 * @method wp_ajax_heartbeat
 * @method wp_ajax_hidden_columns
 * @method wp_ajax_image_editor
 * @method wp_ajax_imgedit_preview
 * @method wp_ajax_inline_save
 * @method wp_ajax_inline_save_tax
 * @method wp_ajax_install_plugin
 * @method wp_ajax_install_theme
 * @method wp_ajax_logged_in
 * @method wp_ajax_menu_get_metabox
 * @method wp_ajax_menu_locations_save
 * @method wp_ajax_menu_quick_search
 * @method wp_ajax_meta_box_order
 * @method wp_ajax_nopriv_heartbeat
 * @method wp_ajax_oembed_cache
 * @method wp_ajax_parse_embed
 * @method wp_ajax_parse_media_shortcode
 * @method wp_ajax_press_this_add_category
 * @method wp_ajax_press_this_save_post
 * @method wp_ajax_query_attachments
 * @method wp_ajax_query_themes
 * @method wp_ajax_replyto_comment
 * @method wp_ajax_sample_permalink
 * @method wp_ajax_save_attachment
 * @method wp_ajax_save_attachment_compat
 * @method wp_ajax_save_attachment_order
 * @method wp_ajax_save_user_color_scheme
 * @method wp_ajax_save_widget
 * @method wp_ajax_save_wporg_username
 * @method wp_ajax_search_install_plugins
 * @method wp_ajax_search_plugins
 * @method wp_ajax_send_attachment_to_editor
 * @method wp_ajax_send_link_to_editor
 * @method wp_ajax_set_attachment_thumbnail
 * @method wp_ajax_set_post_thumbnail
 * @method wp_ajax_test_url
 * @method wp_ajax_time_format
 * @method wp_ajax_trash_post
 * @method wp_ajax_untrash_post
 * @method wp_ajax_update_plugin
 * @method wp_ajax_update_theme
 * @method wp_ajax_update_welcome_panel
 * @method wp_ajax_update_widget
 * @method wp_ajax_upload_attachment
 * @method wp_ajax_widgets_order
 * @method wp_ajax_wp_compression_test
 * @method wp_ajax_wp_fullscreen_save_post
 * @method wp_ajax_wp_link_ajax
 * @method wp_ajax_wp_remove_post_lock
 * @method wp_allow_comment
 * @method wp_allowed_protocols
 * @method wp_array_slice_assoc
 * @method wp_attachment_is
 * @method wp_attachment_is_image
 * @method wp_audio_shortcode
 * @method wp_auth_check
 * @method wp_auth_check_html
 * @method wp_auth_check_load
 * @method wp_authenticate
 * @method wp_authenticate_cookie
 * @method wp_authenticate_email_password
 * @method wp_authenticate_spam_check
 * @method wp_authenticate_username_password
 * @method wp_autosave
 * @method wp_basename
 * @method wp_blacklist_check
 * @method wp_cache_add
 * @method wp_cache_add_global_groups
 * @method wp_cache_add_non_persistent_groups
 * @method wp_cache_close
 * @method wp_cache_decr
 * @method wp_cache_delete
 * @method wp_cache_flush
 * @method wp_cache_get
 * @method wp_cache_incr
 * @method wp_cache_init
 * @method wp_cache_replace
 * @method wp_cache_reset
 * @method wp_cache_set
 * @method wp_cache_switch_to_blog
 * @method wp_calculate_image_sizes
 * @method wp_calculate_image_srcset
 * @method wp_can_install_language_pack
 * @method wp_caption_input_textarea
 * @method wp_category_checklist
 * @method wp_check_browser_version
 * @method wp_check_filetype
 * @method wp_check_filetype_and_ext
 * @method wp_check_for_changed_slugs
 * @method wp_check_invalid_utf8
 * @method wp_check_jsonp_callback
 * @method wp_check_locked_posts
 * @method wp_check_mysql_version
 * @method wp_check_password
 * @method wp_check_php_mysql_versions
 * @method wp_check_post_hierarchy_for_loops
 * @method wp_check_post_lock
 * @method wp_check_term_hierarchy_for_loops
 * @method wp_checkdate
 * @method wp_clean_plugins_cache
 * @method wp_clean_themes_cache
 * @method wp_clean_update_cache
 * @method wp_clear_auth_cookie
 * @method wp_clear_scheduled_hook
 * @method wp_clearcookie
 * @method wp_clone
 * @method wp_color_scheme_settings
 * @method wp_comment_form_unfiltered_html_nonce
 * @method wp_comment_reply
 * @method wp_comment_trashnotice
 * @method wp_constrain_dimensions
 * @method wp_convert_bytes_to_hr
 * @method wp_convert_hr_to_bytes
 * @method wp_convert_widget_settings
 * @method wp_cookie_constants
 * @method wp_count_attachments
 * @method wp_count_comments
 * @method wp_count_posts
 * @method wp_count_terms
 * @method wp_create_categories
 * @method wp_create_category
 * @method wp_create_nav_menu
 * @method wp_create_nonce
 * @method wp_create_post_autosave
 * @method wp_create_tag
 * @method wp_create_term
 * @method wp_create_thumbnail
 * @method wp_create_user
 * @method wp_credits
 * @method wp_cron
 * @method wp_crop_image
 * @method wp_customize_support_script
 * @method wp_customize_url
 * @method wp_dashboard
 * @method wp_dashboard_browser_nag
 * @method wp_dashboard_cached_rss_widget
 * @method wp_dashboard_empty
 * @method wp_dashboard_incoming_links
 * @method wp_dashboard_incoming_links_control
 * @method wp_dashboard_incoming_links_output
 * @method wp_dashboard_plugins
 * @method wp_dashboard_plugins_output
 * @method wp_dashboard_primary
 * @method wp_dashboard_primary_control
 * @method wp_dashboard_primary_output
 * @method wp_dashboard_quick_press
 * @method wp_dashboard_quick_press_output
 * @method wp_dashboard_quota
 * @method wp_dashboard_recent_comments
 * @method wp_dashboard_recent_comments_control
 * @method wp_dashboard_recent_drafts
 * @method wp_dashboard_recent_posts
 * @method wp_dashboard_right_now
 * @method wp_dashboard_rss_control
 * @method wp_dashboard_rss_output
 * @method wp_dashboard_secondary
 * @method wp_dashboard_secondary_control
 * @method wp_dashboard_secondary_output
 * @method wp_dashboard_setup
 * @method wp_dashboard_site_activity
 * @method wp_dashboard_trigger_widget_control
 * @method wp_debug_backtrace_summary
 * @method wp_debug_mode
 * @method wp_default_editor
 * @method wp_default_scripts
 * @method wp_default_styles
 * @method wp_defer_comment_counting
 * @method wp_defer_term_counting
 * @method wp_delete_attachment
 * @method wp_delete_auto_drafts
 * @method wp_delete_category
 * @method wp_delete_comment
 * @method wp_delete_file
 * @method wp_delete_link
 * @method wp_delete_nav_menu
 * @method wp_delete_object_term_relationships
 * @method wp_delete_post
 * @method wp_delete_post_revision
 * @method wp_delete_term
 * @method wp_delete_user
 * @method wp_dequeue_script
 * @method wp_dequeue_style
 * @method wp_deregister_script
 * @method wp_deregister_style
 * @method wp_destroy_all_sessions
 * @method wp_destroy_current_session
 * @method wp_destroy_other_sessions
 * @method wp_die
 * @method wp_doc_link_parse
 * @method wp_download_language_pack
 * @method wp_dropdown_categories
 * @method wp_dropdown_cats
 * @method wp_dropdown_languages
 * @method wp_dropdown_pages
 * @method wp_dropdown_roles
 * @method wp_dropdown_users
 * @method wp_edit_attachments_query
 * @method wp_edit_attachments_query_vars
 * @method wp_edit_posts_query
 * @method wp_editor
 * @method wp_embed_defaults
 * @method wp_embed_excerpt_attachment
 * @method wp_embed_excerpt_more
 * @method wp_embed_handler_audio
 * @method wp_embed_handler_googlevideo
 * @method wp_embed_handler_video
 * @method wp_embed_handler_youtube
 * @method wp_embed_register_handler
 * @method wp_embed_unregister_handler
 * @method wp_encode_emoji
 * @method wp_enqueue_media
 * @method wp_enqueue_script
 * @method wp_enqueue_scripts
 * @method wp_enqueue_style
 * @method wp_exif_date2ts
 * @method wp_exif_frac2dec
 * @method wp_expand_dimensions
 * @method wp_explain_nonce
 * @method wp_ext2type
 * @method wp_extract_urls
 * @method wp_favicon_request
 * @method wp_filesystem
 * @method wp_filter_comment
 * @method wp_filter_kses
 * @method wp_filter_nohtml_kses
 * @method wp_filter_object_list
 * @method wp_filter_oembed_result
 * @method wp_filter_post_kses
 * @method wp_filter_pre_oembed_result
 * @method wp_find_hierarchy_loop
 * @method wp_find_hierarchy_loop_tortoise_hare
 * @method wp_fix_server_vars
 * @method wp_footer
 * @method wp_functionality_constants
 * @method wp_generate_attachment_metadata
 * @method wp_generate_auth_cookie
 * @method wp_generate_password
 * @method wp_generate_tag_cloud
 * @method wp_generator
 * @method wp_get_active_and_valid_plugins
 * @method wp_get_active_network_plugins
 * @method wp_get_all_sessions
 * @method wp_get_archives
 * @method wp_get_associated_nav_menu_items
 * @method wp_get_attachment_caption
 * @method wp_get_attachment_id3_keys
 * @method wp_get_attachment_image
 * @method wp_get_attachment_image_sizes
 * @method wp_get_attachment_image_src
 * @method wp_get_attachment_image_srcset
 * @method wp_get_attachment_image_url
 * @method wp_get_attachment_link
 * @method wp_get_attachment_metadata
 * @method wp_get_attachment_thumb_file
 * @method wp_get_attachment_thumb_url
 * @method wp_get_attachment_url
 * @method wp_get_audio_extensions
 * @method wp_get_available_translations
 * @method wp_get_canonical_url
 * @method wp_get_comment_fields_max_lengths
 * @method wp_get_comment_status
 * @method wp_get_cookie_login
 * @method wp_get_current_commenter
 * @method wp_get_current_user
 * @method wp_get_db_schema
 * @method wp_get_document_title
 * @method wp_get_ext_types
 * @method wp_get_http
 * @method wp_get_http_headers
 * @method wp_get_image_editor
 * @method wp_get_installed_translations
 * @method wp_get_link_cats
 * @method wp_get_links
 * @method wp_get_linksbyname
 * @method wp_get_mime_types
 * @method wp_get_mu_plugins
 * @method wp_get_nav_menu_items
 * @method wp_get_nav_menu_object
 * @method wp_get_nav_menu_to_edit
 * @method wp_get_nav_menus
 * @method wp_get_network
 * @method wp_get_nocache_headers
 * @method wp_get_object_terms
 * @method wp_get_original_referer
 * @method wp_get_password_hint
 * @method wp_get_pomo_file_data
 * @method wp_get_popular_importers
 * @method wp_get_post_autosave
 * @method wp_get_post_categories
 * @method wp_get_post_cats
 * @method wp_get_post_parent_id
 * @method wp_get_post_revision
 * @method wp_get_post_revisions
 * @method wp_get_post_tags
 * @method wp_get_post_terms
 * @method wp_get_raw_referer
 * @method wp_get_recent_posts
 * @method wp_get_referer
 * @method wp_get_revision_ui_diff
 * @method wp_get_schedule
 * @method wp_get_schedules
 * @method wp_get_server_protocol
 * @method wp_get_session_token
 * @method wp_get_shortlink
 * @method wp_get_sidebars_widgets
 * @method wp_get_single_post
 * @method wp_get_sites
 * @method wp_get_split_term
 * @method wp_get_split_terms
 * @method wp_get_term_taxonomy_parent_id
 * @method wp_get_theme
 * @method wp_get_themes
 * @method wp_get_translation_updates
 * @method wp_get_update_data
 * @method wp_get_upload_dir
 * @method wp_get_user_contact_methods
 * @method wp_get_users_with_no_role
 * @method wp_get_video_extensions
 * @method wp_get_widget_defaults
 * @method wp_guess_url
 * @method wp_handle_comment_submission
 * @method wp_handle_sideload
 * @method wp_handle_upload
 * @method wp_hash
 * @method wp_hash_password
 * @method wp_head
 * @method wp_heartbeat_set_suspension
 * @method wp_heartbeat_settings
 * @method wp_html_excerpt
 * @method wp_html_split
 * @method wp_htmledit_pre
 * @method wp_http_supports
 * @method wp_http_validate_url
 * @method wp_iframe
 * @method wp_image_add_srcset_and_sizes
 * @method wp_image_editor
 * @method wp_image_editor_supports
 * @method wp_imagecreatetruecolor
 * @method wp_import_cleanup
 * @method wp_import_handle_upload
 * @method wp_import_upload_form
 * @method wp_initial_constants
 * @method wp_initial_nav_menu_meta_boxes
 * @method wp_insert_attachment
 * @method wp_insert_category
 * @method wp_insert_comment
 * @method wp_insert_link
 * @method wp_insert_post
 * @method wp_insert_term
 * @method wp_insert_user
 * @method wp_install
 * @method wp_install_defaults
 * @method wp_install_language_form
 * @method wp_install_maybe_enable_pretty_permalinks
 * @method wp_installing
 * @method wp_is_ini_value_changeable
 * @method wp_is_large_network
 * @method wp_is_mobile
 * @method wp_is_numeric_array
 * @method wp_is_post_autosave
 * @method wp_is_post_revision
 * @method wp_is_stream
 * @method wp_is_writable
 * @method wp_iso_descrambler
 * @method wp_json_encode
 * @method wp_just_in_time_script_localization
 * @method wp_kses
 * @method wp_kses_allowed_html
 * @method wp_kses_array_lc
 * @method wp_kses_attr
 * @method wp_kses_attr_check
 * @method wp_kses_attr_parse
 * @method wp_kses_bad_protocol
 * @method wp_kses_bad_protocol_once
 * @method wp_kses_bad_protocol_once2
 * @method wp_kses_check_attr_val
 * @method wp_kses_data
 * @method wp_kses_decode_entities
 * @method wp_kses_hair
 * @method wp_kses_hair_parse
 * @method wp_kses_hook
 * @method wp_kses_html_error
 * @method wp_kses_js_entities
 * @method wp_kses_named_entities
 * @method wp_kses_no_null
 * @method wp_kses_normalize_entities
 * @method wp_kses_normalize_entities2
 * @method wp_kses_normalize_entities3
 * @method wp_kses_one_attr
 * @method wp_kses_post
 * @method wp_kses_post_deep
 * @method wp_kses_split
 * @method wp_kses_split2
 * @method wp_kses_stripslashes
 * @method wp_kses_version
 * @method wp_link_category_checklist
 * @method wp_link_manager_disabled_message
 * @method wp_link_pages
 * @method wp_list_authors
 * @method wp_list_bookmarks
 * @method wp_list_categories
 * @method wp_list_cats
 * @method wp_list_comments
 * @method wp_list_filter
 * @method wp_list_pages
 * @method wp_list_pluck
 * @method wp_list_post_revisions
 * @method wp_list_widget_controls
 * @method wp_list_widget_controls_dynamic_sidebar
 * @method wp_list_widgets
 * @method wp_load_alloptions
 * @method wp_load_core_site_options
 * @method wp_load_image
 * @method wp_load_translations_early
 * @method wp_localize_jquery_ui_datepicker
 * @method wp_localize_script
 * @method wp_login
 * @method wp_login_form
 * @method wp_login_url
 * @method wp_login_viewport_meta
 * @method wp_loginout
 * @method wp_logout
 * @method wp_logout_url
 * @method wp_lostpassword_url
 * @method wp_magic_quotes
 * @method wp_mail
 * @method wp_maintenance
 * @method wp_make_content_images_responsive
 * @method wp_make_link_relative
 * @method wp_match_mime_types
 * @method wp_max_upload_size
 * @method wp_maybe_auto_update
 * @method wp_maybe_decline_date
 * @method wp_maybe_generate_attachment_metadata
 * @method wp_maybe_load_embeds
 * @method wp_maybe_load_widgets
 * @method wp_maybe_update_network_site_counts
 * @method wp_maybe_update_network_user_counts
 * @method wp_media_attach_action
 * @method wp_media_insert_url_form
 * @method wp_media_upload_handler
 * @method wp_mediaelement_fallback
 * @method wp_meta
 * @method wp_metadata_lazyloader
 * @method wp_mime_type_icon
 * @method wp_mkdir_p
 * @method wp_nav_menu
 * @method wp_nav_menu_disabled_check
 * @method wp_nav_menu_item_link_meta_box
 * @method wp_nav_menu_item_post_type_meta_box
 * @method wp_nav_menu_item_taxonomy_meta_box
 * @method wp_nav_menu_locations_meta_box
 * @method wp_nav_menu_manage_columns
 * @method wp_nav_menu_max_depth
 * @method wp_nav_menu_post_type_meta_boxes
 * @method wp_nav_menu_setup
 * @method wp_nav_menu_taxonomy_meta_boxes
 * @method wp_nav_menu_update_menu_items
 * @method wp_network_dashboard_right_now
 * @method wp_new_blog_notification
 * @method wp_new_comment
 * @method wp_new_comment_notify_moderator
 * @method wp_new_comment_notify_postauthor
 * @method wp_new_user_notification
 * @method wp_next_scheduled
 * @method wp_no_robots
 * @method wp_nonce_ays
 * @method wp_nonce_field
 * @method wp_nonce_tick
 * @method wp_nonce_url
 * @method wp_normalize_path
 * @method wp_not_installed
 * @method wp_notify_moderator
 * @method wp_notify_postauthor
 * @method wp_ob_end_flush_all
 * @method wp_object_type_exists
 * @method wp_oembed_add_discovery_links
 * @method wp_oembed_add_host_js
 * @method wp_oembed_add_provider
 * @method wp_oembed_ensure_format
 * @method wp_oembed_get
 * @method wp_oembed_register_route
 * @method wp_oembed_remove_provider
 * @method wp_old_slug_redirect
 * @method wp_original_referer_field
 * @method wp_page_menu
 * @method wp_page_reload_on_back_button_js
 * @method wp_parse_args
 * @method wp_parse_auth_cookie
 * @method wp_parse_id_list
 * @method wp_parse_str
 * @method wp_parse_url
 * @method wp_password_change_notification
 * @method wp_playlist_scripts
 * @method wp_playlist_shortcode
 * @method wp_plugin_directory_constants
 * @method wp_plugin_update_row
 * @method wp_plugin_update_rows
 * @method wp_plupload_default_settings
 * @method wp_popular_terms_checklist
 * @method wp_post_mime_type_where
 * @method wp_post_preview_js
 * @method wp_post_revision_title
 * @method wp_post_revision_title_expanded
 * @method wp_pre_kses_less_than
 * @method wp_pre_kses_less_than_callback
 * @method wp_preload_dialogs
 * @method wp_prepare_attachment_for_js
 * @method wp_prepare_revisions_for_js
 * @method wp_prepare_themes_for_js
 * @method wp_print_admin_notice_templates
 * @method wp_print_editor_js
 * @method wp_print_footer_scripts
 * @method wp_print_head_scripts
 * @method wp_print_media_templates
 * @method wp_print_request_filesystem_credentials_modal
 * @method wp_print_revision_templates
 * @method wp_print_scripts
 * @method wp_print_styles
 * @method wp_print_update_row_templates
 * @method wp_protect_special_option
 * @method wp_prototype_before_jquery
 * @method wp_publish_post
 * @method wp_queue_comments_for_comment_meta_lazyload
 * @method wp_queue_posts_for_term_meta_lazyload
 * @method wp_quicktags
 * @method wp_raise_memory_limit
 * @method wp_rand
 * @method wp_read_audio_metadata
 * @method wp_read_image_metadata
 * @method wp_read_video_metadata
 * @method wp_redirect
 * @method wp_redirect_admin_locations
 * @method wp_referer_field
 * @method wp_refresh_post_lock
 * @method wp_refresh_post_nonces
 * @method wp_register
 * @method wp_register_plugin_realpath
 * @method wp_register_script
 * @method wp_register_sidebar_widget
 * @method wp_register_style
 * @method wp_register_widget_control
 * @method wp_registration_url
 * @method wp_rel_nofollow
 * @method wp_rel_nofollow_callback
 * @method wp_remote_fopen
 * @method wp_remote_get
 * @method wp_remote_head
 * @method wp_remote_post
 * @method wp_remote_request
 * @method wp_remote_retrieve_body
 * @method wp_remote_retrieve_cookie
 * @method wp_remote_retrieve_cookie_value
 * @method wp_remote_retrieve_cookies
 * @method wp_remote_retrieve_header
 * @method wp_remote_retrieve_headers
 * @method wp_remote_retrieve_response_code
 * @method wp_remote_retrieve_response_message
 * @method wp_removable_query_args
 * @method wp_remove_object_terms
 * @method wp_replace_in_html_tags
 * @method wp_reschedule_event
 * @method wp_reset_postdata
 * @method wp_reset_query
 * @method wp_reset_vars
 * @method wp_resolve_numeric_slug_conflicts
 * @method wp_resource_hints
 * @method wp_resource_hints_scripts_styles
 * @method wp_restore_image
 * @method wp_restore_post_revision
 * @method wp_revisions_enabled
 * @method wp_revisions_to_keep
 * @method wp_revoke_user
 * @method wp_richedit_pre
 * @method wp_roles
 * @method wp_rss
 * @method wp_safe_redirect
 * @method wp_safe_remote_get
 * @method wp_safe_remote_head
 * @method wp_safe_remote_post
 * @method wp_safe_remote_request
 * @method wp_salt
 * @method wp_sanitize_redirect
 * @method wp_save_image
 * @method wp_save_image_file
 * @method wp_save_nav_menu_items
 * @method wp_save_post_revision
 * @method wp_schedule_event
 * @method wp_schedule_single_event
 * @method wp_schedule_update_checks
 * @method wp_schedule_update_network_counts
 * @method wp_scheduled_delete
 * @method wp_script_add_data
 * @method wp_script_is
 * @method wp_scripts
 * @method wp_send_json
 * @method wp_send_json_error
 * @method wp_send_json_success
 * @method wp_send_new_user_notifications
 * @method wp_set_all_user_settings
 * @method wp_set_auth_cookie
 * @method wp_set_comment_cookies
 * @method wp_set_comment_status
 * @method wp_set_current_user
 * @method wp_set_internal_encoding
 * @method wp_set_lang_dir
 * @method wp_set_link_cats
 * @method wp_set_object_terms
 * @method wp_set_password
 * @method wp_set_post_categories
 * @method wp_set_post_cats
 * @method wp_set_post_lock
 * @method wp_set_post_tags
 * @method wp_set_post_terms
 * @method wp_set_sidebars_widgets
 * @method wp_set_wpdb_vars
 * @method wp_setcookie
 * @method wp_setup_nav_menu_item
 * @method wp_shake_js
 * @method wp_shortlink_header
 * @method wp_shortlink_wp_head
 * @method wp_should_upgrade_global_tables
 * @method wp_shrink_dimensions
 * @method wp_sidebar_description
 * @method wp_signon
 * @method wp_simplepie_autoload
 * @method wp_site_icon
 * @method wp_slash
 * @method wp_spaces_regexp
 * @method wp_spam_comment
 * @method wp_specialchars
 * @method wp_specialchars_decode
 * @method wp_sprintf
 * @method wp_sprintf_l
 * @method wp_ssl_constants
 * @method wp_star_rating
 * @method wp_start_object_cache
 * @method wp_staticize_emoji
 * @method wp_staticize_emoji_for_email
 * @method wp_stream_image
 * @method wp_strip_all_tags
 * @method wp_style_add_data
 * @method wp_style_is
 * @method wp_style_loader_src
 * @method wp_styles
 * @method wp_suspend_cache_addition
 * @method wp_suspend_cache_invalidation
 * @method wp_tag_cloud
 * @method wp_templating_constants
 * @method wp_tempnam
 * @method wp_term_is_shared
 * @method wp_terms_checklist
 * @method wp_text_diff
 * @method wp_theme_update_row
 * @method wp_theme_update_rows
 * @method wp_throttle_comment_flood
 * @method wp_timezone_choice
 * @method wp_timezone_override_offset
 * @method wp_timezone_supported
 * @method wp_tiny_mce
 * @method wp_title
 * @method wp_title_rss
 * @method wp_transition_comment_status
 * @method wp_transition_post_status
 * @method wp_trash_comment
 * @method wp_trash_post
 * @method wp_trash_post_comments
 * @method wp_trim_excerpt
 * @method wp_trim_words
 * @method wp_underscore_audio_template
 * @method wp_underscore_playlist_templates
 * @method wp_underscore_video_template
 * @method wp_unique_filename
 * @method wp_unique_post_slug
 * @method wp_unique_term_slug
 * @method wp_unregister_globals
 * @method wp_unregister_sidebar_widget
 * @method wp_unregister_widget_control
 * @method wp_unschedule_event
 * @method wp_unslash
 * @method wp_unspam_comment
 * @method wp_untrash_comment
 * @method wp_untrash_post
 * @method wp_untrash_post_comments
 * @method wp_update_attachment_metadata
 * @method wp_update_category
 * @method wp_update_comment
 * @method wp_update_comment_count
 * @method wp_update_comment_count_now
 * @method wp_update_core
 * @method wp_update_link
 * @method wp_update_nav_menu_item
 * @method wp_update_nav_menu_object
 * @method wp_update_network_counts
 * @method wp_update_network_site_counts
 * @method wp_update_network_user_counts
 * @method wp_update_plugin
 * @method wp_update_plugins
 * @method wp_update_post
 * @method wp_update_term
 * @method wp_update_term_count
 * @method wp_update_term_count_now
 * @method wp_update_theme
 * @method wp_update_themes
 * @method wp_update_user
 * @method wp_upgrade
 * @method wp_upload_bits
 * @method wp_upload_dir
 * @method wp_user_settings
 * @method wp_using_ext_object_cache
 * @method wp_validate_auth_cookie
 * @method wp_validate_boolean
 * @method wp_validate_logged_in_cookie
 * @method wp_validate_redirect
 * @method wp_verify_nonce
 * @method wp_version_check
 * @method wp_video_shortcode
 * @method wp_welcome_panel
 * @method wp_widget_control
 * @method wp_widget_description
 * @method wp_widget_rss_form
 * @method wp_widget_rss_output
 * @method wp_widget_rss_process
 * @method wp_widgets_access_body_class
 * @method wp_widgets_add_menu
 * @method wp_widgets_init
 * @method wp_write_post
 * @method wpautop
 * @method wpmu_activate_signup
 * @method wpmu_activate_stylesheet
 * @method wpmu_admin_do_redirect
 * @method wpmu_admin_redirect_add_updated_param
 * @method wpmu_checkavailablespace
 * @method wpmu_create_blog
 * @method wpmu_create_user
 * @method wpmu_current_site
 * @method wpmu_delete_blog
 * @method wpmu_delete_user
 * @method wpmu_get_blog_allowedthemes
 * @method wpmu_log_new_registrations
 * @method wpmu_menu
 * @method wpmu_signup_blog
 * @method wpmu_signup_blog_notification
 * @method wpmu_signup_stylesheet
 * @method wpmu_signup_user
 * @method wpmu_signup_user_notification
 * @method wpmu_update_blogs_date
 * @method wpmu_validate_blog_signup
 * @method wpmu_validate_user_signup
 * @method wpmu_welcome_notification
 * @method wpmu_welcome_user_notification
 * @method wptexturize
 * @method wptexturize_primes
 * @method wpview_media_sandbox_styles
 * @method write_post
 * @method xfn_check
 * @method xmlrpc_getpostcategory
 * @method xmlrpc_getposttitle
 * @method xmlrpc_pingback_error
 * @method xmlrpc_removepostdata
 * @method zeroise
 */
class WP
{
    /**
     * @param string $functionName
     * @param array $args
     *
     * @return mixed
     */
    public function __call($functionName, array $args = array())
    {
        $numArgs = count($args);

        if($numArgs < 1) {
            return $functionName();
        } else if($numArgs === 1) {
            return $functionName($args[0]);
        } else if($numArgs === 2) {
            return $functionName($args[0], $args[1]);
        } else if($numArgs === 3) {
            return $functionName($args[0], $args[1], $args[2]);
        } else if($numArgs === 4) {
            return $functionName($args[0], $args[1], $args[2], $args[3]);
        }

        return call_user_func_array($functionName, $args);
    }
}
